deepsoccer: #namespace
    task_and_robot_environment_name: 'MyDeepSoccerSingle-v0'
    ros_ws_abspath: "/home/kimbring2/catkin_ws"
    running_step: 0.04 # amount of time the control will be executed
    pos_step: 0.016     # increment in position for each command
    
    #qlearn parameters
    alpha: 0.1
    gamma: 0.7
    epsilon: 0.9
    epsilon_discount: 0.999
    nepisodes: 500
    nsteps: 10000
    running_step: 0.06 # Time for each step

deepsoccer_test: #namespace
    task_and_robot_environment_name: 'MyDeepSoccerSingleTest-v0'
    ros_ws_abspath: "/home/kimbring2/catkin_ws"
    running_step: 0.04 # amount of time the control will be executed
    pos_step: 0.016     # increment in position for each command
    
    #qlearn parameters
    alpha: 0.1
    gamma: 0.7
    epsilon: 0.9
    epsilon_discount: 0.999
    nepisodes: 500
    nsteps: 10000
    running_step: 0.06 # Time for each step
